swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: Maintain Vacancy Service
    description: Create, Update and delete operations pertaining to vacancies for jobs in Government
paths:
  /vacancy:
    post:
      tags:
        - maintain-vacancy-controller
      summary: create
      operationId: create
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: vacancy
          description: vacancy
          required: true
          schema:
            $ref: '#/definitions/Vacancy'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Vacancy'
    put:
      tags:
        - maintain-vacancy-controller
      summary: update
      operationId: update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: vacancyId
          in: path
          description: vacancyId
          required: true
          type: integer
          format: int64
        - in: body
          name: vacancyUpdate
          description: vacancyUpdate
          required: true
          schema:
            $ref: '#/definitions/Vacancy'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Vacancy'
    delete:
      tags:
        - maintain-vacancy-controller
      summary: delete
      operationId: delete
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: vacancyId
          in: path
          description: vacancyId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Vacancy'
definitions:
  Department:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Page«Vacancy»:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/Vacancy'
      first:
        type: boolean
      last:
        type: boolean
      number:
        type: integer
        format: int32
      numberOfElements:
        type: integer
        format: int32
      size:
        type: integer
        format: int32
      sort:
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
      totalPages:
        type: integer
        format: int32
  Sort:
    type: object
  Vacancy:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      description:
        type: string
      location:
        type: string
      grade:
        type: string
      role:
        type: string
      responsibilities:
        type: string
      workingHours:
        type: string
      closingDate:
        type: string
        example: 'yyyy-MM-ddTHH:mm:ss.SSSZ e.g. 1976-05-26T00:00:00+0000'
      contactName:
        type: string
      contactDepartment:
        type: string
      contactEmail:
        type: string
      contactTelephone:
        type: string
      eligibility:
        type: string
      salaryMin:
        type: integer
        format: int32
      salaryMax:
        type: integer
        format: int32
      numberVacancies:
        type: integer
        format: int32
      governmentOpeningDate:
        type: string
        example: 'yyyy-MM-ddTHH:mm:ss.SSSZ e.g. 1976-05-26T00:00:00+0000'
      internalOpeningDate:
        type: string
        example: 'yyyy-MM-ddTHH:mm:ss.SSSZ e.g. 1976-05-26T00:00:00+0000'
      publicOpeningDate:
        type: string
        example: 'yyyy-MM-ddTHH:mm:ss.SSSZ e.g. 1976-05-26T00:00:00+0000'
      longitude:
        type: number
        format: double
        example: '51.454929'
      latitude:
        type: number
        format: double
        example: '-2.627811'
      department:
        $ref: '#/definitions/Department'
      displayCscContent:
        type: boolean
        description: Whether or not to display the CS Commissioners Content
      selectionProcessDetails:
        type: string
        description: Information about the selection process
