swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: Department Service
    description: Apis relating to deparments
  - name: department-controller
    description: Department Controller
paths:
  /department:
    get:
      tags:
        - department-controller
      summary: Find all departments
      operationId: findAll
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Page«Department»'
    post:
      tags:
        - department-controller
      summary: Create a department
      operationId: create
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: department
          description: department
          required: true
          schema:
            $ref: '#/definitions/Department'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Department'
  '/department/{departmentId}':
    get:
      tags:
        - department-controller
      summary: Find a specific department
      operationId: findById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: departmentId
          in: path
          description: departmentId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Department'
    put:
      tags:
        - department-controller
      summary: Update a department
      operationId: update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: departmentId
          in: path
          description: departmentId
          required: true
          type: integer
          format: int64
        - in: body
          name: departmentUpdate
          description: departmentUpdate
          required: true
          schema:
            $ref: '#/definitions/Department'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Department'
    delete:
      tags:
        - department-controller
      summary: Delete a department
      operationId: delete
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: departmentId
          in: path
          description: departmentId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Department'
definitions:
  Department:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      disabilityLogo:
        type: string
        description: 'There are three levels of disability confident employers, one of "Committed", "Leader", "Employer", or no value'
  Page«Department»:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/Department'
      first:
        type: boolean
      last:
        type: boolean
      number:
        type: integer
        format: int32
      numberOfElements:
        type: integer
        format: int32
      size:
        type: integer
        format: int32
      sort:
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
      totalPages:
        type: integer
        format: int32
  Sort:
    type: object
