swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: Location Service
    description: APIs relating to Location Service
  - name: location-service-controller
    description: Location Service Controller
paths:
  /findlocation:
    get:
      tags:
        - location-service-controller
      summary: >-
        Find latitude and longitude coordinates identifiing where either a
        placename prefix or full or partial postcode is.
      operationId: findLocation
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: searchTerm
          in: path
          description: Place name or full/partial postcode
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Coordinates'
definitions:
  Coordinates:
    type: object
    properties:
      latitude:
        type: number
        format: double
        example: 51.5444326
      longitude:
        type: number
        format: double
        example: -2.4509024

